import { SearchShadowModifier } from "../../common/AttributeModifierConfig"

@Component
export struct SearchComponent {
  @Link searchValue: string
  controller: SearchController | undefined = undefined
  onChange = () => {
  }
  onSubmit = (_value: string) => {
  }
  onEditChange = ((_isEditing: boolean) => {
  })
  onSearchFocus = () => {
  }

  build() {
    Search({
      controller: this.controller,
      placeholder: $r('app.string.search_placeholder'),
      value: $$this.searchValue
    })
      .layoutWeight(1)
      .height(40)
      .clickEffect({ level: ClickEffectLevel.LIGHT, scale: 0.9 })
      .animation({ duration: 300, curve: Curve.Ease })
      .attributeModifier(new SearchShadowModifier())
      .keyboardAppearance(KeyboardAppearance.IMMERSIVE)// 设置搜索框沉浸模式
      .onChange(() => {
        this.onChange()
      })
      .onSubmit((value: string) => {
        this.onSubmit(value)
      })
      .onEditChange((isEditing: boolean) => {
        this.onEditChange(isEditing)
      })
      .onFocus(() => {
        this.onSearchFocus()
      })
  }
}